schema-version = 1
release-version = "8.2.0-0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.anishchk]
registry = "037235346509.dkr.ecr.us-west-2.amazonaws.com"

[sdk]
name = "bottlerocket-sdk"
version = "0.61.0"
vendor = "bottlerocket"
